#!/usr/bin/env bash
set -euo pipefail

# ================================================================
# mac-setup.sh — Run on Cloud9 to generate a Mac setup script
#
# Usage (on Cloud9):
#   ./mac-setup.sh > /tmp/mac-connect.sh
#   cat /tmp/mac-connect.sh   # copy-paste to Mac, or scp it
# ================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

if [ ! -f terraform.tfvars ]; then echo "ERROR: terraform.tfvars not found in $SCRIPT_DIR"; exit 1; fi

# Resolve all endpoints from Terraform state
EKS_NAME=$(terraform output -raw eks_cluster_name 2>/dev/null)
EKS_REGION=$(grep aws_region terraform.tfvars | awk -F'"' '{print $2}')
SQL_ENDPOINT=$(terraform output -raw sqlserver_endpoint 2>/dev/null)
SQL_HOST=$(echo "$SQL_ENDPOINT" | cut -d: -f1)
SQL_PORT=$(echo "$SQL_ENDPOINT" | cut -d: -f2)
SQL_USER=$(grep sqlserver_username terraform.tfvars | awk -F'"' '{print $2}')
PG_ENDPOINT=$(terraform output -raw aurora_pg_endpoint 2>/dev/null)
PG_HOST=$(echo "$PG_ENDPOINT" | cut -d: -f1)
PG_PORT=$(echo "$PG_ENDPOINT" | cut -d: -f2)
PG_USER=$(grep aurora_username terraform.tfvars | awk -F'"' '{print $2}')
PG_DB=$(grep aurora_db_name terraform.tfvars | awk -F'"' '{print $2}')

cat <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# ================================================================
# Mac connect script — generated by mac-setup.sh on Cloud9
#
# Usage:
#   ./mac-connect.sh          # one-time setup + port-forwards
#   ./mac-connect.sh ports    # port-forwards only (kill + restart)
# ================================================================

CMD="${1:-setup}"

trap 'kill_port_forwards; exit 0' INT TERM

HEADER

cat <<EOF
# ── Helper: kill existing port-forwards ──────────────────────────
kill_port_forwards() {
  echo "Killing existing port-forwards..."
  # Kill kubectl port-forward processes targeting EKS/Confluent/monitoring/flink
  pkill -f "kubectl port-forward.*-n confluent" 2>/dev/null || true
  pkill -f "kubectl port-forward.*-n monitoring" 2>/dev/null || true
  pkill -f "kubectl port-forward.*-n flink" 2>/dev/null || true
  sleep 1
}

# ── Helper: start port-forwards ──────────────────────────────────
pf() {
  if kubectl get svc "\$1" -n "\$2" > /dev/null 2>&1; then
    kubectl port-forward "svc/\$1" -n "\$2" "\$3" 2>/dev/null &
    echo "  ✓ \$1 → localhost:\${3%%:*}"
  else
    echo "  - \$1 (not found, skipping)"
  fi
}

start_port_forwards() {
  echo "Starting port-forwards..."
  echo ""
  pf controlcenter    confluent  9021:9021
  pf schemaregistry   confluent  8081:8081
  pf connect          confluent  8083:8083
  pf kube-prometheus-stack-grafana monitoring 3000:80
  pf cmf-service      flink      8090:80

  echo ""
  echo "════════════════════════════════════════════════════════"
  echo "  Port-forwards active:"
  echo ""
  echo "  Connect REST             http://localhost:8083"
  echo "  Schema Registry          http://localhost:8081"
  echo "  Control Center           http://localhost:9021"
  echo "  Grafana                  http://localhost:3000  (admin/admin)"
  echo "  Flink CMF                http://localhost:8090"
  echo "════════════════════════════════════════════════════════"
  echo ""
  echo "  Ctrl+C to stop port-forwards."
}

# ── Port-forwards only ───────────────────────────────────────────
if [ "\$CMD" = "ports" ]; then
  kill_port_forwards
  start_port_forwards
  wait || true
  exit 0
fi

# ── One-time setup ───────────────────────────────────────────────
# ── EKS ────────────────────────────────────────────────────────
echo "Configuring kubectl for EKS..."
aws eks update-kubeconfig \\
  --name ${EKS_NAME} \\
  --region ${EKS_REGION}

echo "Verifying cluster access..."
kubectl get nodes

# ── Database connection details ────────────────────────────────
# SQL Server (DBeaver / sqlcmd)
export CDC_SQL_HOST="${SQL_HOST}"
export CDC_SQL_PORT="${SQL_PORT}"
export CDC_SQL_USER="${SQL_USER}"
# Password: set manually or export CDC_SQL_PASS="..."
echo ""
echo "SQL Server:"
echo "  Host: ${SQL_HOST}"
echo "  Port: ${SQL_PORT}"
echo "  User: ${SQL_USER}"
echo ""

# Aurora PostgreSQL (DBeaver / psql)
export CDC_PG_HOST="${PG_HOST}"
export CDC_PG_PORT="${PG_PORT}"
export CDC_PG_USER="${PG_USER}"
export CDC_PG_DB="${PG_DB}"
# Password: set manually or export CDC_PG_PASS="..."
echo "Aurora PostgreSQL:"
echo "  Host: ${PG_HOST}"
echo "  Port: ${PG_PORT}"
echo "  User: ${PG_USER}"
echo "  DB:   ${PG_DB}"
echo ""

# ── Port forwards ────────────────────────────────────────────────
kill_port_forwards
start_port_forwards

echo ""
echo "  DBeaver SQL Server       ${SQL_HOST}:${SQL_PORT}"
echo "  DBeaver Aurora PG        ${PG_HOST}:${PG_PORT}"
echo ""

wait || true
EOF
